var AS = $rdf.Namespace('https://www.w3.org/ns/activitystreams#')
var BOOK = $rdf.Namespace('http://www.w3.org/2002/01/bookmark#')
var DCT = $rdf.Namespace('http://purl.org/dc/terms/')
var FOAF = $rdf.Namespace('http://xmlns.com/foaf/0.1/')
var RDF = $rdf.Namespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#')
var SIOC = $rdf.Namespace('http://rdfs.org/sioc/ns#')
var SOLID = $rdf.Namespace('http://www.w3.org/ns/solid/terms#')
var VCARD = $rdf.Namespace('http://www.w3.org/2006/vcard/ns#')
